wdmc-nitj/nitj-site

index.html
js/app.js
js/navbar-mobile.js
js/navbar.js
style.css

Addressed the issues #26 #27 #29 #30 #31 #33

resolved navbar issues

---

index.html
package-lock.json
style.css
yarn.lock

Reverts wdmc-nitj/nitj-site#51

Revert "Gallery section added"

---

admissions/antiRagging.html
admissions/student_life.html
common template/navbar.html
style.css

Anti Ragging and Student life Completed

Anti Ragging and Student life Completed

---

common template/navbar.html
style.css

Team D- Admission and Research Tabs. Changes in both tabs updated

Changes in  Admission and Research in tabs

---

common template/navbar.html

Reverts wdmc-nitj/nitj-site#79

Revert "academic add"

---

admin/hostels.html
admin/senate.html

Reverts wdmc-nitj/nitj-site#83
Bhavya have already incorporated these changes in his pages

Revert "senate data"

---

admin/administration.html
admin/chairperson.html
admin/committees.html
admin/council.html
admin/director.html
admin/explore.html
admin/governors.html
admin/hostels.html
admin/index.html
admin/location.html
admin/oc.html
admin/ranking.html
admin/registrar.html
admin/senate.html
admin/virtualtour.html
common template/navbar.html
style.css

Changed font of Different pages
Added senate content
Change in title of Pages (hostels etc)
Explore Nitj js resolved
Other issues resolves

Merging Final Changes

---

admin/committees.html
admin/governors.html
admin/registrar.html
admin/students.html
common template/navbar.html

Student.html created
Registrars problem solved
Governor page issues
Committee page issues corrected (added bhavika's code)

Issues Resolved and New Pages Added

---

js/dept-controller.js

Reverts wdmc-nitj/nitj-site#122

Revert "Update dept-controller.js"

---

admin/committees.html
admin/students.html

Added Rakesh Sir in Student.html
Changed ordering of committees page

changes in student.html and Committees.html

---

admin/administration.html

addition of third tab for associate deans.....id changes are pending

deans page - added third dean tab

---

admin/administration.html
admin/building_works.html
admin/finance_committee.html
admin/senate.html
style.css

finance 
building works
senate pages modification

Restructuring senate pages 

---

admin/administration.html

correction for administration page tabs

administration page

---

admin/administration.html

Administration page change in case

---

alumni/alumni.html
alumni/register.html

Reverts wdmc-nitj/nitj-site#224

Revert "alumni portal changes"

---

admin/proctorial-cell.html

To maintain uniformity grade-1 or II has been removed in designation

Removed grades in designation

---

admin/assitant_registrar.html
admin/assitant_registrar_old.html
admin/women-cell.html

women cell and AR page update

---

js/data.js

Description was linked to cards. changed to title

Research highlights update

---

index.html

phd dot is added and tab of student corner and upcoming event is changed

small typos and tab change

---

js/data.js

total description will come backend

removed club added to the type

---

index.html
js/app.js
js/data.js
js/routing.js
js/utils/app/scrollUtils.js
js/utils/app/tabUits.js
js/utils/routingUtils.js

- Testimonial UI Updated
- Clubs and socs updated
- News section
- Blue color on the top
- Tabs section changes

UI changes all across the site

---

admin/students.html

final changes
